### PR TITLE
New pr

### PR DESCRIPTION
**Pull request by steph-crown**

### CODE REVIEW

**Comment by Acel-01** [comment]
You sent a PR for adding one line to the read.me?
I won't merge this kind of PR next time oo

**Comment by Acel-01** [comment]
Also, next time add a description to your PR? 
How do you expect me to know what you worked on? 
I'm not omniscient na

**Comment by steph-crown** [comment]
Ma binu.
I'm just learning how to create prs.
Just wanted to see if you could view it.
Thanks

**Comment by Acel-01** [comment]
okay sir 
You're welcome

**Pull request merged**
